### ISSUE TITLE
ObjectId comparison

### ISSUE THREAD

**Issue by stalniy** [aptivator/mongo-query-compiler#1]
this returns wrong result:
```js
const ObjectId = require('mongoose').Types.ObjectId
const compile = require('mongo-query-compiler')
const id = ObjectId()

const matches = compile({ id })

console.log(matches({ id: id.toString() })) //false
console.log(matches({ id: ObjectId(id.toString()) })) //false
```
I expect both checks to return true. 

Is there anyway to check equality of `ObjectId`s?

**Comment by aptivator** [comment]
The utility was originally written to work in a browser environment to help streamline filtering of some relatively complex arrays.  Support for ObjectId was outside of the spec.  Adding the functionality for the latter should be trivial.  I am always happy to consider pull requests.

**Comment by stalniy** [comment]
Could you please point me to some place where I can read how to add customo functionality?

**Comment by aptivator** [comment]
It seems that the logical place to add the functionality is in the [$eq](https://github.com/aptivator/mongo-query-compiler/blob/master/src/lib/evl/operations/primitive/components/eq.js) file.  However, other operators are likely to be affected also (e.g., $in, $type).  I'll leave it to you to find the best ObjectId library to use (on the server and in the browser) and to assure that operations are compatible with mongodb driver's ObjectId.  Please include all the necessary tests to accompany the changes.
