### ISSUE TITLE
compileMongoQuery must work with null and {}

### ISSUE THREAD

**Issue by ianengelbrecht** [aptivator/mongo-query-compiler#2]
According to the [mongodb docs](https://www.mongodb.com/docs/drivers/node/current/usage-examples/find/), find() should allow for null or empty objects and return all records in these cases. The current implementation of compileMongoQuery doesn't cater for this. It could be fixed quite simply by returning `function() return true` early on in the code if null or {} are passed in.

**Comment by aptivator** [comment]
You'll have to elaborate more on the use case for this feature.  In other words, there is an array of objects and the query object for that is either null or {}.  That means there is nothing to query.  In your code you can just return the array itself or its duplicate, etc.  What is the point  of running .filter() with a function that will instruct to return every single element of that array?  The purpose of mongo-query-compiler is to compile an actual query.  At this point I don't see how this should be within a purview of the library.

**Comment by ianengelbrecht** [comment]
Yes you're correct, my suggestion was only to make the API consistent with the mongo API, which does allow {} to be passed in as an argument.
