### ISSUE TITLE
$in: [empy array] returns all documents

### ISSUE THREAD

**Issue by ianengelbrecht** [aptivator/mongo-query-compiler#3]
Sorry to be loading issues in tonight. It looks like a query selector with $in and an empty array, as below returns all values in the array being filtered. I think it it should return none, although I can't specifically find that stated in the Mongo documentation. 

```
{
  fieldname: {
    $in: []
  }
}
```

**Comment by aptivator** [comment]
That has been fixed and I've published version 1.0.5.
